#ifndef WEB_CLI_H
#define WEB_CLI_H

String getCLIPage(const String& username) {
  String inner;
  inner.reserve(6000);
  inner += "<style>";
  inner += ".cli-container {";
  inner += "  background: rgba(0, 0, 0, 0.3);";
  inner += "  border-radius: 15px;";
  inner += "  padding: 25px;";
  inner += "  backdrop-filter: blur(10px);";
  inner += "  border: 1px solid rgba(255, 255, 255, 0.1);";
  inner += "  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.2);";
  inner += "  font-family: 'Courier New', monospace;";
  inner += "  width: 95%;";
  inner += "  max-width: 1400px;";
  inner += "  margin: 0 auto;";
  inner += "}";
  inner += ".cli-header {";
  inner += "  text-align: center;";
  inner += "  font-size: 1.5em;";
  inner += "  margin-bottom: 20px;";
  inner += "  color: #4CAF50;";
  inner += "  font-weight: bold;";
  inner += "}";
  inner += ".cli-output {";
  inner += "  background: rgba(0, 0, 0, 0.5);";
  inner += "  border: 1px solid #333;";
  inner += "  border-radius: 5px;";
  inner += "  padding: 15px;";
  inner += "  height: 400px;";
  inner += "  overflow-y: auto;";
  inner += "  margin-bottom: 15px;";
  inner += "  font-size: 14px;";
  inner += "  line-height: 1.4;";
  inner += "  white-space: pre-wrap;";
  inner += "  color: #fff;";
  inner += "  scroll-behavior: smooth;";
  inner += "}";
  inner += ".cli-input-container {";
  inner += "  display: flex;";
  inner += "  align-items: center;";
  inner += "  gap: 10px;";
  inner += "}";
  inner += ".cli-prompt {";
  inner += "  color: #4CAF50;";
  inner += "  font-weight: bold;";
  inner += "}";
  inner += ".cli-input {";
  inner += "  flex: 1 1 320px;";
  inner += "  min-width: 160px;";
  inner += "  width: auto;";
  inner += "  background: rgba(255,255,255,0.08);";
  inner += "  border: 1px solid rgba(255,255,255,0.25);";
  inner += "  color: #fff;";
  inner += "  font-family: 'Courier New', monospace;";
  inner += "  font-size: 14px;";
  inner += "  outline: none;";
  inner += "  padding: 6px 8px;";
  inner += "  border-radius: 6px;";
  inner += "  margin-bottom: 0;";
  inner += "  display: block;";
  inner += "  position: relative;";
  inner += "  z-index: 2;";
  inner += "  pointer-events: auto;";
  inner += "  box-sizing: border-box;";
  inner += "}";
  inner += ".help-text {";
  inner += "  margin-top: 15px;";
  inner += "  font-size: 12px;";
  inner += "  color: #ccc;";
  inner += "  font-style: italic;";
  inner += "}";
  inner += "</style>";
  
  inner += "<div class='cli-container'>";
  inner += "  <div class='cli-header'>HardwareOne Command Line Interface</div>";
  inner += "  <div id='cli-output' class='cli-output'></div>";
  inner += "  <div class='cli-input-container'>";
  inner += "    <span class='cli-prompt'>$</span>";
  inner += "    <input type='text' id='cli-input' class='cli-input' placeholder='Enter command...' autocomplete='off'>";
  inner += "    <button id='cli-exec' class='btn'>Execute</button>";
  inner += "  </div>";
  inner += "  <div class='help-text'>Press Enter to execute commands | Type 'help' for command list | Authenticated as: " + username + "</div>";
  inner += "</div>";
  
  inner += "<script>";
  inner += "try{console.log('[CLI] Script A start');}catch(_){}";
  inner += "var cliInput = document.getElementById('cli-input');";
  inner += "var cliOutput = document.getElementById('cli-output');";
  inner += "var cliExecBtn = document.getElementById('cli-exec');";
  inner += "window.addEventListener('error', function(e){ try { if(cliOutput){ cliOutput.textContent += ('[JS Error] ' + e.message + '\\n'); cliOutput.scrollTop = cliOutput.scrollHeight; } } catch(_){} });";
  inner += "var commandHistory = []; var historyIndex = -1; var currentCommand=''; var outputHistory=''; var inHelp=false; var outputBackup='';";
  inner += "if(cliExecBtn){ cliExecBtn.addEventListener('click', function(){ if(window.executeCommand) executeCommand(); }); }";
  inner += "if(cliInput){ cliInput.addEventListener('keydown', function(e){ if(e.key==='Enter' && window.executeCommand){ executeCommand(); } }); }";
  inner += "try{console.log('[CLI] Script A ready');}catch(_){}";
  inner += "</script>";

  inner += "<script>";
  inner += "try{console.log('[CLI] Script B start');}catch(_){}";
  inner += "try{ commandHistory = JSON.parse(localStorage.getItem('cliHistory') || '[]'); }catch(_){ commandHistory = []; }";
  inner += "historyIndex = -1; currentCommand = '';";
  inner += "try{ outputHistory = localStorage.getItem('cliOutputHistory') || ''; }catch(_){ outputHistory=''; }";
  inner += "try{ inHelp = JSON.parse(localStorage.getItem('cliInHelp') || 'false'); }catch(_){ inHelp=false; }";
  inner += "try{ outputBackup = localStorage.getItem('cliOutputHistoryBackup') || ''; }catch(_){ outputBackup=''; }";
  inner += "if (outputHistory && cliOutput) { cliOutput.textContent = outputHistory; cliOutput.scrollTop = cliOutput.scrollHeight; }";
  inner += "if(cliInput){ cliInput.addEventListener('keydown', function(e){";
  inner += "  if (e.key === 'ArrowUp') { e.preventDefault(); if (historyIndex === -1) { currentCommand = cliInput.value; } if (historyIndex < commandHistory.length - 1) { historyIndex++; cliInput.value = commandHistory[commandHistory.length - 1 - historyIndex]; } }";
  inner += "  else if (e.key === 'ArrowDown') { e.preventDefault(); if (historyIndex > 0) { historyIndex--; cliInput.value = commandHistory[commandHistory.length - 1 - historyIndex]; } else if (historyIndex === 0) { historyIndex = -1; cliInput.value = currentCommand; } }";
  inner += "}); }";
  inner += "try{console.log('[CLI] Script B ready');}catch(_){}";
  inner += "</script>";

  inner += "<script>";
  inner += "try{console.log('[CLI] Script C start');}catch(_){}";
  inner += "function executeCommand(){";
  inner += "  try { console.debug('[CLI] execute start'); } catch(_){}";
  inner += "  var command = (cliInput && cliInput.value ? cliInput.value : '').trim();";
  inner += "  if (!command) return;";
  inner += "  var lower = command.toLowerCase();";
  inner += "  var exitingHelp = false;";
  inner += "  if (!inHelp && (lower === 'help' || lower === 'menu' || lower === 'cli help')) {";
  inner += "    outputBackup = cliOutput ? cliOutput.textContent : '';";
  inner += "    try{ localStorage.setItem('cliOutputHistoryBackup', outputBackup); }catch(_){}";
  inner += "    inHelp = true; try{ localStorage.setItem('cliInHelp', 'true'); }catch(_){}";
  inner += "  } else if (inHelp && (lower === 'exit' || lower === 'back' || lower === 'q' || lower === 'quit')) {";
  inner += "    exitingHelp = true;";
  inner += "  }";
  inner += "  if (commandHistory[commandHistory.length - 1] !== command) {";
  inner += "    commandHistory.push(command); if (commandHistory.length > 50) commandHistory.shift();";
  inner += "    try{ localStorage.setItem('cliHistory', JSON.stringify(commandHistory)); }catch(_){}";
  inner += "  }";
  inner += "  historyIndex = -1; currentCommand = '';";
  inner += "  if (cliOutput) { cliOutput.textContent += ('$ ' + command + '\\n'); }";
  inner += "  try { console.debug('[CLI] fetch start'); } catch(_){}";
  inner += "  fetch('/api/cli', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, credentials: 'same-origin', body: 'cmd=' + encodeURIComponent(command) })";
  inner += "  .then(function(r){ return r.text(); })";
  inner += "  .then(function(result){ try { console.debug('[CLI] fetch ok, len=' + (result ? result.length : 0)); } catch(_){} var ESC=String.fromCharCode(27); var clearSeq = ESC+'[2J'+ESC+'[H'; if (result && result.indexOf(clearSeq) !== -1) { var cleanResult = result.split(clearSeq).join(''); if (exitingHelp && inHelp) { if (cliOutput) { cliOutput.textContent = outputBackup || ''; } inHelp = false; try{ localStorage.setItem('cliInHelp','false'); localStorage.removeItem('cliOutputHistoryBackup'); }catch(_){} if (cleanResult && cliOutput) { cliOutput.textContent += cleanResult; } try{ localStorage.setItem('cliOutputHistory', cliOutput ? cliOutput.textContent : ''); }catch(_){} } else { if (cliOutput) { cliOutput.textContent = cleanResult; try{ localStorage.setItem('cliOutputHistory', cliOutput.textContent); }catch(_){} } } } else { if (cliOutput) { cliOutput.textContent += result + '\\n'; try{ localStorage.setItem('cliOutputHistory', cliOutput.textContent); }catch(_){} } } if (cliOutput) cliOutput.scrollTop = cliOutput.scrollHeight; if (cliInput) { cliInput.value=''; cliInput.focus(); } })";
  inner += "  .catch(function(e){ try { console.debug('[CLI] fetch error: ' + e.message); } catch(_){} var errorMsg='Error: ' + e.message + '\\n'; if (cliOutput) { cliOutput.textContent += errorMsg; cliOutput.scrollTop = cliOutput.scrollHeight; try{ localStorage.setItem('cliOutputHistory', cliOutput.textContent); }catch(_){} } if (cliInput) { cliInput.value=''; cliInput.focus(); } });";
  inner += "}";
  inner += "try { console.debug('[CLI] script end marker'); } catch(_){}";
  inner += "function clearHistory() {";
  inner += "  localStorage.removeItem('cliHistory');";
  inner += "  localStorage.removeItem('cliOutputHistory');";
  inner += "  commandHistory = [];";
  inner += "  cliOutput.textContent = '';";
  inner += "  historyIndex = -1;";
  inner += "}";
  inner += "</script>";
  
  return htmlShellWithNav(username, "cli", inner);
}


#endif
