#ifndef WEB_FILES_H
#define WEB_FILES_H

String getFilesPage(const String& username) {
  String inner;
  inner += "<h2>File Manager</h2>";
  inner += "<p>Browse and manage files on the device filesystem</p>";
  
  // File operations toolbar
  inner += "<div style='background:#f8f9fa;padding:1rem;border-radius:8px;margin:1rem 0;border-left:4px solid #667eea'>";
  inner += "  <div style='display:flex;gap:1rem;flex-wrap:wrap;align-items:center'>";
  inner += "    <button class='btn' onclick='createFolder()'>Create Folder</button>";
  inner += "    <button class='btn' onclick='createFile()'>Create File</button>";
  inner += "    <button class='btn' onclick='refreshFiles()'>Refresh</button>";
  inner += "  </div>";
  inner += "</div>";
  
  // File editor modal
  inner += "<div id='editor-modal' style='display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);z-index:1001'>";
  inner += "  <div style='position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);background:white;padding:1rem;border-radius:8px;min-width:720px;max-width:90vw;max-height:90vh;display:flex;flex-direction:column'>";
  inner += "    <div style='display:flex;align-items:center;justify-content:space-between;margin-bottom:0.5rem'>";
  inner += "      <h3 id='editor-title' style='margin:0;color:#000'>Edit File</h3>";
  inner += "      <button class='btn' onclick=\"closeEditor()\">Close</button>";
  inner += "    </div>";
  inner += "    <div style='font-size:0.9rem;color:#333;margin-bottom:0.25rem'><span id='editor-path'></span></div>";
  inner += "    <textarea id='editor-text' style='flex:1;min-height:300px;width:70vw;max-width:85vw;box-sizing:border-box;padding:0.75rem;border:1px solid #ccc;border-radius:6px;font-family:Menlo,Consolas,monospace;font-size:13px;line-height:1.4;color:#000;background:#fff;'></textarea>";
  inner += "    <div style='margin-top:0.6rem;display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap'>";
  inner += "      <button id='editor-save' class='btn' onclick=\"saveEditor()\">Save</button>";
  inner += "      <button id='btn-pretty' class='btn' onclick=\"prettyJSON()\" style='display:none'>Pretty JSON</button>";
  inner += "      <button id='btn-raw' class='btn' onclick=\"rawJSON()\" style='display:none'>Raw JSON</button>";
  inner += "      <span id='editor-status' style='color:#555'></span>";
  inner += "    </div>";
  inner += "  </div>";
  inner += "</div>";
  
  // File list container
  inner += "<div id='file-list' style='background:#f8f9fa;padding:1rem;border-radius:8px;margin:1rem 0;color:#333'>Loading files...</div>";
  
  // File creation modal
  inner += "<div id='file-modal' style='display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.5);z-index:1000'>";
  inner += "  <div style='position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);background:white;padding:2rem;border-radius:8px;min-width:400px;color:#000'>";
  inner += "    <h3 id='modal-title' style='color:#000'>Create File</h3>";
  inner += "    <label>Name:<br><input id='file-name' style='width:100%;padding:0.5rem;margin:0.5rem 0;color:#000;background:#fff;border:1px solid #ccc'></label><br>";
  inner += "    <label>Type:<br><select id='file-type' style='width:100%;padding:0.5rem;margin:0.5rem 0;color:#000;background:#fff;border:1px solid #ccc'>";
  inner += "      <option value='txt'>Text File (.txt)</option>";
  inner += "      <option value='csv'>CSV File (.csv)</option>";
  inner += "      <option value='rtf'>Rich Text (.rtf)</option>";
  inner += "    </select></label><br>";
  inner += "    <div style='margin-top:1rem'>";
  inner += "      <button class='btn' onclick='submitFileCreate()'>Create</button>";
  inner += "      <button class='btn' onclick='closeModal()' style='margin-left:0.5rem'>Cancel</button>";
  inner += "    </div>";
  inner += "  </div>";
  inner += "</div>";
  
  inner += "<script>";
  inner += "window.onload = function() { refreshFiles(); };";
  inner += "let currentPath = '/';";
  inner += "let currentEditPath = '';";
  inner += "let isJsonEdit = false;";
  inner += "function refreshFiles() {";
  inner += "  fetch('/api/files/list?path=' + encodeURIComponent(currentPath)).then(r => r.json()).then(d => {";
  inner += "    if (d.success) {";
  inner += "      let html = '<div style=\"margin-bottom:1rem\">';";
  inner += "      html += '<strong>Current Path:</strong> ' + currentPath;";
  inner += "      if (currentPath !== '/') {";
  inner += "        html += ' <button onclick=\"navigateUp()\" class=\"btn\" style=\"margin-left:1rem\">← Back</button>';";
  inner += "      }";
  inner += "      html += '</div>';";
  inner += "      html += '<table style=\"width:100%;border-collapse:collapse\">';";
  inner += "      html += '<tr style=\"background:#e9ecef\"><th style=\"padding:0.5rem;text-align:left\">Name</th><th style=\"padding:0.5rem;text-align:left\">Type</th><th style=\"padding:0.5rem;text-align:left\">Size</th><th style=\"padding:0.5rem;text-align:left\">Actions</th></tr>';";
  inner += "      d.files.forEach(f => {";
  inner += "        html += '<tr style=\"border-bottom:1px solid #ddd\">';";
  inner += "        if (f.type === 'folder') {";
  inner += "          html += '<td style=\"padding:0.5rem\"><a href=\"#\" onclick=\"enterFolder(\\'' + f.name + '\\')\" style=\"color:#007bff;text-decoration:none\">📁 ' + f.name + '</a></td>';";
  inner += "        } else {";
  inner += "          html += '<td style=\"padding:0.5rem\">📄 ' + f.name + '</td>';";
  inner += "        }";
  inner += "        html += '<td style=\"padding:0.5rem\">' + f.type + '</td>';";
  inner += "        if (f.type === 'folder') {";
  inner += "          const cnt = (typeof f.count === 'number') ? (f.count + ' items') : (f.size || '—');";
  inner += "          html += '<td style=\"padding:0.5rem\">' + cnt + '</td>';";
  inner += "        } else {";
  inner += "          html += '<td style=\"padding:0.5rem\">' + (f.size || '0 bytes') + '</td>';";
  inner += "        }";
  inner += "        html += '<td style=\"padding:0.5rem\">';";
  inner += "        if (f.type === 'folder') {";
  inner += "          html += '<button onclick=\"enterFolder(\\'' + f.name + '\\')\" class=\"btn\" style=\"margin-right:0.5rem\">Enter</button>';";
  inner += "          if (f.name !== 'logs') {";
  inner += "            html += '<button onclick=\"deleteFolder(\\'' + f.name + '\\')\" class=\"btn\">Delete</button>';";
  inner += "          }";
  inner += "        } else {";
  inner += "          const fullPath = (currentPath === '/' ? '/' + f.name : currentPath + '/' + f.name);";
  inner += "          const isProtected = (f.name === 'users.json' || f.name === 'settings.json');";
  inner += "          const isInLogs = (fullPath.startsWith('/logs/'));";
  inner += "          html += '<button onclick=\"viewFile(\\'' + f.name + '\\')\" class=\"btn\" style=\"margin-right:0.5rem\">View</button>';";
  inner += "          if (!isProtected && !isInLogs) {";
  inner += "            html += '<button onclick=\"editFile(\\'' + f.name + '\\')\" class=\"btn\" style=\"margin-right:0.5rem\">Edit</button>';";
  inner += "            html += '<button onclick=\"deleteFile(\\'' + f.name + '\\')\" class=\"btn\">Delete</button>';";
  inner += "          }";
  inner += "        }";
  inner += "        html += '</td></tr>';";
  inner += "      });";
  inner += "      html += '</table>';";
  inner += "      document.getElementById('file-list').innerHTML = html;";
  inner += "    } else {";
  inner += "      document.getElementById('file-list').innerHTML = 'Error: ' + d.error;";
  inner += "    }";
  inner += "  }).catch(e => document.getElementById('file-list').innerHTML = 'Error: ' + e.message);";
  inner += "}";
  inner += "function createFolder() {";
  inner += "  let name = prompt('Folder name:');";
  inner += "  if (name) {";
  inner += "    let fullPath = currentPath === '/' ? '/' + name : currentPath + '/' + name;";
  inner += "    const cmd = 'mkdir ' + fullPath;";
  inner += "    fetch('/api/cli', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'cmd=' + encodeURIComponent(cmd) })";
  inner += "    .then(r => r.text()).then(t => { alert(t || 'Folder created'); refreshFiles(); }).catch(e => alert('Error: ' + e.message));";
  inner += "  }";
  inner += "}";
  inner += "function createFile() {";
  inner += "  document.getElementById('file-modal').style.display = 'block';";
  inner += "}";
  inner += "function closeModal() {";
  inner += "  document.getElementById('file-modal').style.display = 'none';";
  inner += "}";
  inner += "function submitFileCreate() {";
  inner += "  let name = document.getElementById('file-name').value;";
  inner += "  let type = document.getElementById('file-type').value;";
  inner += "  if (name) {";
  inner += "    let fullPath = currentPath === '/' ? '/' + name : currentPath + '/' + name;";
  inner += "    if (type && type !== 'txt' && !fullPath.endsWith('.' + type)) { fullPath = fullPath + '.' + type; }";
  inner += "    const cmd = 'filecreate ' + fullPath;";
  inner += "    fetch('/api/cli', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'cmd=' + encodeURIComponent(cmd) })";
  inner += "    .then(r => r.text()).then(t => { alert(t || 'File created'); closeModal(); refreshFiles(); }).catch(e => alert('Error: ' + e.message));";
  inner += "  }";
  inner += "}";
  inner += "function enterFolder(name) {";
  inner += "  if (currentPath === '/') {";
  inner += "    currentPath = '/' + name;";
  inner += "  } else {";
  inner += "    currentPath = currentPath.endsWith('/') ? currentPath + name : currentPath + '/' + name;";
  inner += "  }";
  inner += "  refreshFiles();";
  inner += "}";
  inner += "function navigateUp() {";
  inner += "  let lastSlash = currentPath.lastIndexOf('/');";
  inner += "  if (lastSlash > 0) {";
  inner += "    currentPath = currentPath.substring(0, lastSlash);";
  inner += "  } else {";
  inner += "    currentPath = '/';";
  inner += "  }";
  inner += "  refreshFiles();";
  inner += "}";
  inner += "function viewFile(name) {";
  inner += "  let fullPath = currentPath === '/' ? '/' + name : currentPath + '/' + name;";
  inner += "  window.open('/api/files/view?name=' + encodeURIComponent(fullPath), '_blank');";
  inner += "}";
  inner += "function editFile(name) {";
  inner += "  currentEditPath = (currentPath === '/' ? '/' + name : currentPath + '/' + name);";
  inner += "  document.getElementById('editor-title').textContent = 'Edit File';";
  inner += "  document.getElementById('editor-path').textContent = currentEditPath;";
  inner += "  document.getElementById('editor-status').textContent = 'Loading...';";
  inner += "  document.getElementById('editor-text').value = '';";
  inner += "  document.getElementById('editor-modal').style.display = 'block';";
  inner += "  isJsonEdit = currentEditPath.toLowerCase().endsWith('.json');";
  inner += "  document.getElementById('btn-pretty').style.display = isJsonEdit ? 'inline-block' : 'none';";
  inner += "  document.getElementById('btn-raw').style.display = isJsonEdit ? 'inline-block' : 'none';";
  inner += "  fetch('/api/files/read?name=' + encodeURIComponent(currentEditPath)).then(r=>r.text()).then(txt=>{ document.getElementById('editor-text').value = txt; document.getElementById('editor-status').textContent=''; }).catch(e=>{ document.getElementById('editor-status').textContent = 'Error: ' + e.message; });";
  inner += "}";
  inner += "function closeEditor(){ document.getElementById('editor-modal').style.display = 'none'; }";
  inner += "function saveEditor(){";
  inner += "  const content = document.getElementById('editor-text').value;";
  inner += "  if (isJsonEdit) {";
  inner += "    try { JSON.parse(content); } catch (e) { document.getElementById('editor-status').textContent = 'Invalid JSON: ' + e.message; return; }";
  inner += "  }";
  inner += "  document.getElementById('editor-status').textContent = 'Saving...';";
  inner += "  fetch('/api/files/write', { method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'}, body: 'name=' + encodeURIComponent(currentEditPath) + '&content=' + encodeURIComponent(content) })";
  inner += "    .then(r=>r.json()).then(j=>{ if(j && j.success){ document.getElementById('editor-status').textContent='Saved.'; refreshFiles(); } else { document.getElementById('editor-status').textContent = 'Error: ' + (j && j.error ? j.error : 'Unknown'); } })";
  inner += "    .catch(e=>{ document.getElementById('editor-status').textContent = 'Error: ' + e.message; });";
  inner += "}";
  inner += "function prettyJSON(){ if(!isJsonEdit) return; const ta=document.getElementById('editor-text'); try{ const obj=JSON.parse(ta.value); ta.value = JSON.stringify(obj, null, 2); document.getElementById('editor-status').textContent='Pretty-printed JSON.'; } catch(e){ document.getElementById('editor-status').textContent='Invalid JSON: ' + e.message; } }";
  inner += "function rawJSON(){ if(!isJsonEdit) return; const ta=document.getElementById('editor-text'); try{ const obj=JSON.parse(ta.value); ta.value = JSON.stringify(obj); document.getElementById('editor-status').textContent='Minified JSON.'; } catch(e){ document.getElementById('editor-status').textContent='Invalid JSON: ' + e.message; } }";
  inner += "function deleteFile(name) {";
  inner += "  let fullPath = currentPath === '/' ? '/' + name : currentPath + '/' + name;";
  inner += "  if (confirm('Delete ' + name + '?')) {";
  inner += "    const cmd = 'filedelete ' + fullPath;";
  inner += "    fetch('/api/cli', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'cmd=' + encodeURIComponent(cmd) })";
  inner += "    .then(r => r.text()).then(t => { alert(t || 'Deleted.'); refreshFiles(); }).catch(e => alert('Error: ' + e.message));";
  inner += "  }";
  inner += "}";
  inner += "function deleteFolder(name) {";
  inner += "  let fullPath = currentPath === '/' ? '/' + name : currentPath + '/' + name;";
  inner += "  if (confirm('Delete folder ' + name + '? Only empty folders can be removed.')) {";
  inner += "    const cmd = 'rmdir ' + fullPath;";
  inner += "    fetch('/api/cli', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: 'cmd=' + encodeURIComponent(cmd) })";
  inner += "    .then(r => r.text()).then(t => { alert(t || 'Folder removed.'); refreshFiles(); }).catch(e => alert('Error: ' + e.message));";
  inner += "  }";
  inner += "}";
  inner += "</script>";
  
  return htmlShellWithNav(username, "files", inner);
}

#endif
